language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
before_script:
    - make install
script: make tests
matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm
notifications:
    irc: 'irc.freenode.org#thefox'
    on_success: never
    on_failure: always