language: php
php:
    - 7.0
    - 7.1
install: 
    - make install
before_script:
    - phpenv rehash
script: make test
env:
    global:
        - COMPOSER_OPTIONS='--prefer-source --no-interaction'
